# Generated by Django 3.0.4 on 2020-04-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('idea', 'Idea'), ('appeal', 'Appeal'), ('opportunity', 'Opportunity')], default='idea', max_length=12),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
