# Generated by Django 3.0.4 on 2020-04-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200402_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='postal',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='notice',
            name='proximity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
