# Generated by Django 3.0.4 on 2020-04-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20200415_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='state',
            new_name='province',
        ),
    ]
