# Generated by Django 3.0.4 on 2020-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20200415_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Province or State'),
        ),
    ]
